package com.ainuribatov.learnandroid

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity(R.layout.activity_main) {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val recyclerView = findViewById<RecyclerView>(R.id.userListRecyclerView)
        recyclerView.layoutManager =
            LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false)
        val adapter = UserAdapter()
        recyclerView.adapter = adapter
        adapter.userList = loadUsers()
        adapter.notifyDataSetChanged()
    }

    private fun loadUsers(): List<UserData> {
        return listOf(
            UserData(avatarUrl = "", userName = "Aidar", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Ainur", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Kirill", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Sasha", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Denil", groupName = "Б10"),
            UserData(avatarUrl = "", userName = "Saveliy", groupName = "Б09"),
            UserData(avatarUrl = "", userName = "Danya", groupName = "Б09"),
        )
    }
}